version: "3.9"
services: 

  teachu-mysql-db:
    container_name: teachu-mysql-db
    build: 
      context: ./teachu-api/
      dockerfile: docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_ALLOW_EMPTY_PASSWORD=true # change when using as prod
      - MYSQL_RANDOM_ROOT_PASSWORD=false
      # custom user
      - MYSQL_USER='dev'
      - MYSQL_PASS='dev'
    networks:
      - teachu
    ports: 
      - "3306:3306"  
    volumes: 
      - teachu-data:/var/lib/mysql

  teachu-api:
    container_name: teachu-api
    build: 
      context: teachu-api
      dockerfile: Dockerfile
    depends_on:
      - teachu-mysql-db
    networks:
      - teachu
    ports:
      - "8080:8080"
    volumes:
      - local-maven-repo:/var/local/.m2

  teachu-client: 
    container_name: teachu-client
    build: 
      context: teachu-client
      dockerfile: Dockerfile
      args:
        - ngConfig=development
    depends_on:
      - teachu-api   
      - teachu-mysql-db 
    networks:
      - teachu
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./teachu-client/.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./teachu-client/.nginx/mime.types:/etc/nginx/mime.types
      
networks:
  teachu:

volumes:
  teachu-data:
  local-maven-repo: