version: '3.9'

services:
  teachu-mysql-db:
    container_name: teachu-mysql-db
    build:
      context: .
      dockerfile: teachu-data/Dockerfile
      args:
        - STARTUP_SCRIPTS_DIR=./teachu-data/docs
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_RANDOM_ROOT_PASSWORD=false
      - MYSQL_USER='dev'
      - MYSQL_PASS='dev'
    networks:
      - net-teachu-data 
    volumes: 
      - vol-teachu-data:/var/lib/mysql
      - ./teachu-data/sql.cnf:/etc/my.cnf

  teachu-api:
    container_name: teachu-api
    build: "teachu-api"
    depends_on:
      - teachu-mysql-db
    networks:
      - net-teachu-data
      - net-teachu

  teachu-client: 
    container_name: teachu-client
    build: 
      context: teachu-client
      dockerfile: Dockerfile
      args:
        - ngConfig=production
    depends_on:
      - teachu-api   
      - teachu-mysql-db 
    networks:
      - net-teachu
    volumes:
      - ./teachu-client/.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./teachu-client/.nginx/mime.types:/etc/nginx/mime.types     

  teachu-admin-server:
    container_name: teachu-admin-server
    build: "teachu-admin/teachu_admin/teachu_admin.server.app.war"
    depends_on:
      - teachu-mysql-db
    networks:
      - net-teachu-data
      - net-teachu
    volumes:
      - type: bind
        source: ./teachu-admin/teachu_admin/docker/logs/server-log
        target: /usr/local/tomcat/logs    

  teachu-admin:
    container_name: teachu-admin
    build: "teachu-admin/teachu_admin/teachu_admin.ui.html.app.war"
    depends_on:
      - teachu-admin-server
    networks:
      - net-teachu-data
      - net-teachu
    volumes:
      - type: bind
        source: ./teachu-admin/teachu_admin/docker/logs/ui-log
        target: /usr/local/tomcat/logs  

  teachu-proxy:
    container_name: teachu-proxy
    image: nginx:stable
    depends_on:
      - teachu-client
      - teachu-admin
    tty: true
    networks:
      - net-teachu
    ports:
      - "80:80"
    volumes:
      - ./teachu-proxy/root-nginx.conf:/etc/nginx/nginx.conf
      - ./teachu-client/.nginx/mime.types:/etc/nginx/mime.types          

networks:
  net-teachu-data:  
  net-teachu:

volumes:
  vol-teachu-data: